apiVersion: v1
kind: Service
metadata:
    name: menopause
    namespace: default
spec:
  ports:
  - port: 80
    name: main
    protocol: TCP
    targetPort: 80
  - port: 27017
    name: mongodb
    protocol: TCP
    targetPort: 27017
  selector:
    app: menopause
  type: LoadBalancer
